### PR TITLE
module for pmem native code and jni

### PR DESCRIPTION
**Pull request by yeyuqiang**
Separate memkind api from unsafe module.

### CODE REVIEW

**Comment by winningsix** [comment]
Thanks @yeyuqiang for the PR. So the plan here is first abstract this module and then move to OAP?

**Comment by yeyuqiang** [comment]
> Thanks @yeyuqiang for the PR. So the plan here is first abstract this module and then move to OAP?

Yes. But still need re-fact the code and add more unit test / examples to make it robust and general enough.

**Comment by winningsix** [comment]
> Yes. But still need re-fact the code and add more unit test / examples to make it robust and general enough.

I suggest OAP (https://github.com/intel-bigdata/oap) side refactor would be the first step. Then depend it in Spark.

**Comment by winningsix** [comment]
Two comments per discussed: 1) make it as a package 2) limit the changes to JNI part considering the short time frame in OAP 0.8 release.

**Comment by yeyuqiang** [comment]
Will send the PR to OAP. Close it

**Pull request closed without merging**
