### PR TITLE
enable parser specific analyzer and optimizer

### PR DESCRIPTION
**Pull request by adrian-wang**
We have to make a few changes to spark to run our parser for user to use as simple as possible.
@chenghao-intel @happycherry

### CODE REVIEW

**Comment by happycherry** [comment]
retest this,please.

**Comment by happycherry** [comment]
retest this please.

**Comment by happycherry** [comment]
retest this please.

**Comment by happycherry** [comment]
retest this please.

**Comment by adrian-wang** [comment]
┐（─__─）┌

**Pull request closed without merging**
