### PR TITLE
Revert "Merge RDD Cache code from branch-2.4.4-oap-0.8 (#27)"

### PR DESCRIPTION
**Pull request by yeyuqiang**

### CODE REVIEW

**Comment by yeyuqiang** [comment]
@zhixingheyi-tian @winningsix @jikunshang

**Comment by winningsix** [comment]
LGTM +1

**Comment by zhixingheyi-tian** [comment]
@yeyuqiang @winningsix 
Would you please revert the commit instead of submitting a PR.

**Comment by jikunshang** [comment]
LGTM

**Pull request merged**
